# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn run build
    - name: ssh deploy
      # You may pin to the exact commit or the version.
      # uses: easingthemes/ssh-deploy@c711f2c3391cac2876bf4c833590077f02e4bcb8
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
        # Private Key
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        # Remote host
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        # Remote user
        REMOTE_USER: ${{ secrets.SSH_USERNAME }}
        # Remote port
        REMOTE_PORT: 22
        # Source directory
        SOURCE: build/*
        # Target directory
        TARGET: /home/liucan/webstorm/svg-drawing-board/
        # Arguments to pass to rsync
        #ARGS: # optional, default is -rltgoDzvO
        # An array of folder to exclude
        #EXCLUDE: # optional, default is 
  
